image: node:18

stages:
  - install
  - build

cache:
  paths:
    - node_modules/

install_dependencies:
  stage: install
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/

build_react_app:
  stage: build
  script:
    - npm run build
  artifacts:
    paths:
      - build/
  only:
    - main
